// Az eredeti ELEMZES/*.dat állományok Windows-1250 → UTF-8 átirata.
// A történeti forrásszövegeket megőrizzük, beleértve a szerző helyesírását.
export const datLibrary: Record<string, string> = {
  "111": "Dinamikus energetikában hiány.\nGyüjti a stressz hatású élményeket, mert belső ellentmondásban van.\nStressz okozó: idő, rend, terv felburulás.",
  "112": "Reaktív. balesetveszélyes helyzeteket vonz magához\nérzelmi átélés kapcsán.\nBetegség: túltengéses.",
  "113": "Agresszívitás jellemzi.\nMagas balesetveszély.\nBetegség: túltengéses.",
  "114": "Visszatarthatatlan. Agresszívitás jellemzi.\nBetegség: pszihoszomatikus eredetüek.\nSzervrendszer problémák.",
  "115": "Magas kockázat és balesetveszély. Hosszantartó terhelést nem bírja.\nBetegség: a test bal oldalán és az agy jobb oldalán.\nTúltengés az ellentkező oldalon.",
  "116": "Kicsi a terhelhetőség.\nEnergia maximális felhasználása jellemzi.\nBetegség: 1,2,4,5 csakrák energiáját emészti fel.",
  "117": "Érzékeny, sértődékeny, bosszúálló.\nÉrzelmileg függ a könyezetétől.\nMagas vegetetív tartalékok.",
  "121": "Hiánybetegségek a test jobb, vagy az agy bal oldalán.\nHa a vezetői igényei nem realizálódnak,  betegségei elsősorban  pszihoszomatikus eredetüek.",
  "122": "Kommunikatív problémák egyre erősödnek.\nIntegráció fekborul amint megjelenik a stressz.\nÉrzelmileg demokratikus vezető.",
  "123": "Nagyon egészséges, de ha sokáig agresszív közegben van vegetatív problémák léphetnek fel.\nGyorsan átkapcsolodik fékezési és élénkítési folyamatokra.\nHumora van.",
  "124": "Kellemetlen típus. Hisztérikus.\nMotorika erős szenzorika gyengült.\nHúgy és nemi jellegű problémák.",
  "125": "A szokásai fontosak számára és nehezen tud megszabadulni tőlük.\nProblémáia társadalni kapcsolatok felbomlásából adódhatnak.",
  "126": "Önző, emelt önértékelés.\nEmelt élékíthetőség. \"Csillagbetegség\".\nA szívközpont erős, minden más gyenge.",
  "127": "A szívközpont túltengéssel dolgozik, minden más hiánnyal.\nMániákus állapotok lehetségesek.",
  "131": "Stressz hatására cselekedetei nem adekváltak.\nRossz az adaptációja.\nSzívközpontnál problémák.",
  "132": "Nagyon sértődékeny.\nStressznél specifikus ellenállás nő, kifárad.\nSzív-és érrendszer gyengült.",
  "133": "Dekoncentráltság jellemzi.\nKülső stimulusok határozzák meg a betegség lefolyását.\nMagas az idegrendszer ereje, de nem kiegyensúlyozott, nem kitartó, más emberektől függ.",
  "134": "Hős nem adekvált.\nTúltengéses betegségek jellemzik, hisztéria.\nSzív-és érrendszer, húgy-és nemi rendszer gyengült.",
  "135": "Alkalmazkodó képessége (adaptáció) nem túl magas.\nKülső közegtől függ az átszabályozás.\nSzív-és érrendszer gyengült.",
  "136": "Hajlamos az önrombolásra.\nJobb oldalon túltengés, bal oldalon hiány.\nBetegség: a test bal oldalán.",
  "137": "Rendkívül érzékeny, beteges.\nGyenge vegetatív idegrendszer.\nMagas érzékenysége miatt paradox reakció.",
  "141": "Túltengéses betegségek a test bal oldalán jelentkeznek.\nKrónikus betegségek a test jobb oldalán várhatóak.\nBetegségek: máj, vese, mellékvese.",
  "142": "Túltengéses betegségek jellemzik.\nA test bal oldala sérülékeny.\nBetegségek: hasnyálmirigy problémák.",
  "143": "Magas érzelmi ellenállás.\nA külső közeggel való harmónia felbomlása stresszhez vezet.\nStressz hatására a külső közeg megváltozik, magasak az elvárásai magához és máshoz.",
  "144": "Emelkedett intraverzió.\nFügg a külső közegtől, stressz-gyűjtés jellemzi.\nHiperaktivitásra hajlamos, nehezen alszik, pihen.",
  "145": "Természeti tipológiája egyensúlyban van.\nStressz-okozó, harmónia felbomlása.\nHarmónia felbomlása esetén betegségek: betegségcsoport keríti hatalmába.",
  "146": "Hajlamos a kockázatvállalásra, traumaveszély fenyegeti.\nStressz-oldás lényeges.\nMeg kell tanulnia az ellazulást.",
  "147": "Önszerető, nagyon érzékeny.\nBetegségeinek fő oka komforthiány a családban és társadalomban.\nFontos a jó kommunikáció kialakítása.",
  "151": "Sztereotip viselkedésű.\nHajlamos a pedantikus ismétlődő folyamatok elfogadására.\nBetegség esetén depresszív állapotba kerülhet.",
  "152": "\"Magammal ragadom\" - ez jellemzi tevékenységét.\nEgészségét elsősorban az új szituációkhoz való alkalmazkodás törheti meg.\nBetegség: adaptációs problémák.",
  "153": "Magas aktivitása kompenzálja az adaptációt.\nHa a mozgás nem biztosított, maga a gyógyulás folyamata legyen változatos.\nBetegség esetén nem kényszeríthetjük fekvésre.",
  "154": "Gyenge a test bal oldala és a jobb agyfélteke.\nElsősorban a szív-és érrendszer valamint a gyomor és hasnyálmirigy betegségekre fogékony.",
  "155": "Harmonikus.\t\t\t\t\t\nÉrzelmi függőség, visszafogottság jellemzi.\nStressz-gyűjtő, de jó az ellenálló képessége.",
  "156": "Ingerlékeny.\nStressz után nehezen tud megnyugodni.\nBetegség: szív-és érrendszer, hormonális, anyagcsere problémák léphetnek fel.",
  "157": "Hipochonder. Nagy érzelmi feszültségek jellemzik.\nA hormonális rendszer felbomlása okozhat megbetegedést.\nBetegségéből való gyógyulást másoktól várja.",
  "161": "Inert, vegetatív tartalékok alacsonyak.\nÖsszegyüjti stresszt, majd robban.\nNehéz megmozgatni, ha kimozdult nehéz megnyugtatni.",
  "162": "Erős temperamentum, hideg érzelem.\nÉrzelmi terhelés esetén váratlan reakciók.\nÁllapotváltoztatás csak szakaszosan, lassan.",
  "163": "Érzelmileg durva.\nMagas energetikája miatt az  érzelmi terhelés esetén váratlan reakciók.\nAz érzelmi tartalékokat nagyon gyorsan letöri.",
  "164": "Érzelmi stressz esetén, apátia.\nEnergia túlhasználás.\nA fekezés folyamatának, adaptációnak a törése.",
  "165": "Alacsony ellenállóképesség.\nAlacsony integrációs képesség.\nStresszokozó: a szociális vagy társadalmi közeg változása.",
  "166": "Szubjektív, kiegyensúlyozattlan.\nBelső konfliktusban van.\nHisztérikus reakciók lehetségesek.",
  "167": "Védtelenség, hipochondria.\nA betegségeket összegyüjti, alcsony tűrési határ.\nTartalékok hiánya jellemzi.",
  "211": "Okos, erős kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nNem verbális módszerek fogadására alkalmas.\t\t\nAsztrális, mentális programozás (napfény, víz, fák, növények) hatékony.",
  "212": "Okos, erős kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nAsztrális és mentális önprogramozást a mindennapi életébe kell beépíteni,\nmagas önprogramozási képesség jellemzi.",
  "213": "Okos, erős kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nNehéz vele a munka mivel nagyon erős az energetikája.\t\t\nJó az önszabályozó képessége.\nNem egy hálás típus – ’Ezt én csináltam.’",
  "214": "Okos, erős kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nSértődékeny.\t\t\t\nHatásos a verbális, energetikai (impulzusszerűen) módszerek.",
  "215": "Okos, erős kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nAsztrális és mentális önprogramozásra, és fizikai gyakorlatokra képes.\t\t\t\nBetegségei általában az életmódjával kapcsolatosak.",
  "216": "Okos, erős kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nVerbálisan programozható.\nAsztrális, mentális önprogramozás jellemzi. Mezőráhatásokra érzékeny.",
  "217": "Okos, erős kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nAz intellektum kiegyenlíti a temperamentum lehetőségeit.\t\nÉrzelmi támogatásra van szüksége.",
  "221": "Képzelőerő, asztrális szintű programozás.\nTermészeti képeket használjunk (kép, zene, színekkel való munka).\nNyugodt tényezőkkel, periódikusan ismétlődő módszerekkel dolgozzunk.",
  "222": "Képzelőerő, asztrális szintű programozás.\nAsztrális programozás, képek és természeti komponensek felhasználásával.\nRendszeres fizikai gyakorlatok fontosak.",
  "223": "Képzelőerő, asztrális szintű programozás.\nErős saját energetikája van.\t\t\t\t\nLegjobb megtanítani neki az energetikai gyakorlatokat.",
  "224": "Képzelőerő, asztrális szintű programozás.\nAsztrális programozásra, képekkel való munkára fogékonnyá tenni.",
  "225": "Képzelőerő, asztrális szintű programozás.\nÉrzékeny, beképzeli a betegségeket.\t\t\t\t\t\nAsztrális és energetikai programozás.",
  "226": "Képzelőerő, asztrális szintű programozás.\nIngerlékeny, állandó stressz-állapotban van.\nGondolatban pszichológiai fészket kell találni neki, ahol elrejtőzhet.",
  "227": "Képzelőerő, asztrális szintű programozás.\nHipochonder, érzékeny, a minimális ingereket is megérzi.\nPszicho-fizikai tréningek hatásosak.",
  "231": "Logikus bloksémák, mentális progr., torziós mezőkkel való munka fontos.\nFontos a munkák stabilitása, természeti rendszerekkel dolgozhatunk.\nFontos hogy a gyógykezelési programja ne változzon.\nEl kell juttatni a programot a páciens tudatáig, hogy azután saját maga ismételhesse.",
  "232": "Logikus bloksémák, mentális progr., torziós mezőkkel való munka fontos.\nVerbális és nem verbális munkamódszerek.\nFontos a munka stabilitása, ezen típus számára hasznos a programban visszatérő formákat alkalmazunk.",
  "233": "Logikus bloksémák, mentális progr., torziós mezőkkel való munka fontos.\nNagyon magas a kritikai gát.\nJó a verbális munkamódszer: ima, ének.\nFontos a saját energetikájának aktiválása.’Saját magát gyógyítja.’",
  "234": "Logikus bloksémák, mentális progr., torziós mezőkkel való munka fontos.\nVerbális szuggesztív programozás, különösen a mentális síkon.\t\nImpulzusos energetikai ráhatás.",
  "235": "Logikus bloksémák, mentális progr., torziós mezőkkel való munka fontos.\nMagas az önszabályozási képessége, ezért minden módszert ezen keresztül kell végig vezetni.",
  "236": "Logikus bloksémák, mentális progr., torziós mezőkkel való munka fontos.\nJól irányítható verbális módszerekkel.\nMentális programozás.\nFigyelmet kell fordítani a túlfeszültség levételére.",
  "237": "Logikus bloksémák, mentális progr., torziós mezőkkel való munka fontos.\nStabil, megváltozhatatlan programmal kell dolgozni vele, önhelyreállításra kell helyezni a hangsúlyt.",
  "241": "Rendkívüli pedantizmus jellemzi (a gyógyítóra is ez legyen a jellemző).\nRészletesen, pontosan, logikusan kell a programot elmondani.",
  "242": "Minden munkamódszer hatékony vele, ha szuggesztív ráhatást alkalmazunk.\nHa verbális ráhatással dolgozunk, akkor energetikai módszerrel is ki kell egészíteni (saját energetikájával).",
  "243": "Verbális, vokális módszerrel és mentális programozással dolgozhatunk.\nDinamikus pszichoenergetikai módszereket is alkalmazhatunk.",
  "244": "Krónikus betegségek a baloldalon fognak jelentkezni.\nVerbális programozást alkalmazhatunk.\nEnergetikai ráhatást a gyengébbik oldalra, majd elosztjuk.",
  "245": "Önszabályozásra alkalmas, mert magas a tudati szintje.\nVerbális, mentális programozást alkalmazhatunk, energetikai módszer kiegészítésével.",
  "246": "Verbális módszerekkel rá kell vezetni a pozitív hozzáállásra.\nMentális programozást is alkalmazhatunk.\nKorrigálni kell az önszabályozását.",
  "247": "Magas érzékenység jellemzi.\nVerbális, logikai meggyőzést kell alkalmaznunk.\nMentális, verbális munkamódszerek alkalmazhatóak.\nEnergetikára nagyon érzékeny, vigyázni a dózis nagyságára.",
  "251": "Lassú eredmény várható.\nTermészeti módszereket és mentális programozást alkalmazhatunk.",
  "252": "Nagyon erős a struktúrája.\nAsztrális, mentális programozást alkalmazhatunk, (képek, zene) energetikai módszerek kiegészítésével.\nFontos az energetikájának a harmonizálása.",
  "253": "Fizikai módszereket alkalmazhatunk (kontakt nélküli masszás, pont masszás, fizikai gyakorlatok).\nAsztrális, mentális módszereket is alkalmazhatunk (fizikai tartalékok aktivizálása).",
  "254": "A fékezés erejét kell növelni.\nMeg kell tanítani ellazulni.\nVerbális, asztrális, mentális programmódszereket alkalmazhatunk.",
  "255": "A környezeti hatások könnyen átprogramozzák. Asztrális, mentális\nprogramozással stabil programot alkalmazzunk. Fennáll a betegség \nvisszatérésének veszélye.",
  "256": "Könnyen irányítható,szuggesztív módszerekkel.\nSzámára a dinamikus programok a megfelelőek.\nLe kell venni a feszültséget, időt kell hagyni az ellazulásra.",
  "257": "Állandó érzelmi támogatásra szorul.\nNe érje egyszerre nagy dózisú energetikai ráhatás, csak fokozatosan növeljük az energiát.",
  "261": "Mentális programozás.\nLerontja a saját temperamentumát.\nPszichofizikai gyakorlatokat és energetikai ráhatást alkalmazhatunk.",
  "262": "Mentális programozás.\nNehéz bekapcsolni a munkába.\t\nPszichofizikai gyakorlatokat és természeti erőket alkalmazhatunk (víz, fitoterápia).",
  "263": "Mentális programozás.\nMinden fizikai módszert alkalmazhatunk, verbális ráhatás kombinálásával.\nÉrzelmi kapaszkodók lényegesek.",
  "264": "Mentális programozás.\nParancsszerű utasításokkal dolgozhatunk, az érzelmi megerősítés fontos (erre épüljön az egész program).",
  "265": "Mentális programozás.\nNem kritikus.\nA túlprogramozás veszélye fennállhat (a betegség visszatérhet).",
  "266": "Mentális programozás.\nA munka fizikai, érzelmi kontúr mentén a leghatékonyabb.",
  "267": "Mentális programozás.\nAprólékos, magyarázó munkamódszert alkalmazzunk, érzelmi támogatással.\nÉrzékeny, nem magabiztos.",
  "271": "Asztrális programozás.\nLerontja a saját temperamentumát.\nPszichofizikai gyakorlatokat és energetikai ráhatást alkalmazhatunk.",
  "272": "Asztrális programozás.\nNehéz bekapcsolni a munkába.\t\nPszichofizikai gyakorlatokat és természeti erőket alkalmazhatunk (víz, fitoterápia).",
  "273": "Asztrális programozás.\nMinden fizikai módszert alkalmazhatunk, verbális ráhatás kombinálásával.\nÉrzelmi kapaszkodók lényegesek.",
  "274": "Asztrális programozás.\nParancsszerű utasításokkal dolgozhatunk, az érzelmi megerősítés fontos (erre épüljön az egész program).",
  "275": "Asztrális programozás.\nNem kritikus.\t\t\t\t\t\t\t\t\nA túlprogramozás veszélye fennállhat (a betegség visszatérhet).",
  "276": "Asztrális programozás.\nA munka fizikai, érzelmi kontúr mentén a leghatékonyabb.",
  "277": "Asztrális programozás.\nAprólékos, magyarázó munkamódszert alkalmazzunk, érzelmi támogatással.\nÉrzékeny, nem magabiztos."
};
