// A Tipologia-new csomag ELEMZES könyvtárának ISO-8859-1 -> UTF-8 átemelése.
export const datLibrary: Record<string, string> = {
  "111": "Dinamikus energetikában hiány.\nGyüjti a stressz hatású élményeket, mert belsõ ellentmondásban van.\nStressz okozó: idõ, rend, terv felburulás.",
  "112": "Reaktív. balesetveszélyes helyzeteket vonz magához\nérzelmi átélés kapcsán.\nBetegség: túltengéses.",
  "113": "Agresszívitás jellemzi.\nMagas balesetveszély.\nBetegség: túltengéses.\n\n",
  "114": "Visszatarthatatlan. Agresszívitás jellemzi.\nBetegség: pszihoszomatikus eredetüek.\nSzervrendszer problémák.\n\n",
  "115": "Magas kockázat és balesetveszély. Hosszantartó terhelést nem bírja.\nBetegség: a test bal oldalán és az agy jobb oldalán.\nTúltengés az ellentkezõ oldalon.",
  "116": "Kicsi a terhelhetõség.\nEnergia maximális felhasználása jellemzi.\nBetegség: 1,2,4,5 csakrák energiáját emészti fel.",
  "117": "Érzékeny, sértõdékeny, bosszúálló.\nÉrzelmileg függ a könyezetétõl.\nMagas vegetetív tartalékok.",
  "121": "Hiánybetegségek a test jobb, vagy az agy bal oldalán.\nHa a vezetõi igényei nem realizálódnak,  betegségei elsõsorban  pszihoszomatikus eredetüek.",
  "122": "Kommunikatív problémák egyre erõsödnek.\nIntegráció fekborul amint megjelenik a stressz.\nÉrzelmileg demokratikus vezetõ.",
  "123": "Nagyon egészséges, de ha sokáig agresszív közegben van vegetatív problémák léphetnek fel.\nGyorsan átkapcsolodik fékezési és élénkítési folyamatokra.\nHumora van.",
  "124": "Kellemetlen típus. Hisztérikus.\nMotorika erõs szenzorika gyengült.\nHúgy és nemi jellegû problémák.",
  "125": "A szokásai fontosak számára és nehezen tud megszabadulni tõlük.\nProblémáia társadalni kapcsolatok felbomlásából adódhatnak.\n",
  "126": "Önzõ, emelt önértékelés.\nEmelt élékíthetõség. \"Csillagbetegség\".\nA szívközpont erõs, minden más gyenge.",
  "127": "A szívközpont túltengéssel dolgozik, minden más hiánnyal.\nMániákus állapotok lehetségesek.",
  "131": "Stressz hatására cselekedetei nem adekváltak.\nRossz az adaptációja.\nSzívközpontnál problémák.\n",
  "132": "Nagyon sértõdékeny.\nStressznél specifikus ellenállás nõ, kifárad.\nSzív-és érrendszer gyengült.\n",
  "133": "Dekoncentráltság jellemzi.\nKülsõ stimulusok határozzák meg a betegség lefolyását.\nMagas az idegrendszer ereje, de nem kiegyensúlyozott, nem kitartó, más emberektõl függ.\n",
  "134": "Hõs nem adekvált.\nTúltengéses betegségek jellemzik, hisztéria.\nSzív-és érrendszer, húgy-és nemi rendszer gyengült.\n",
  "135": "Alkalmazkodó képessége (adaptáció) nem túl magas.\nKülsõ közegtõl függ az átszabályozás.\nSzív-és érrendszer gyengült.\n",
  "136": "Hajlamos az önrombolásra.\nJobb oldalon túltengés, bal oldalon hiány.\nBetegség: a test bal oldalán.\n",
  "137": "Rendkívül érzékeny, beteges.\nGyenge vegetatív idegrendszer.\nMagas érzékenysége miatt paradox reakció.\n",
  "141": "Túltengéses betegségek a test bal oldalán jelentkeznek.\nKrónikus betegségek a test jobb oldalán várhatóak.\nBetegségek: máj, vese, mellékvese.\n",
  "142": "Túltengéses betegségek jellemzik.\nA test bal oldala sérülékeny.\nBetegségek: hasnyálmirigy problémák.\n",
  "143": "Magas érzelmi ellenállás.\nA külsõ közeggel való harmónia felbomlása stresszhez vezet.\nStressz hatására a külsõ közeg megváltozik, magasak az elvárásai magához és máshoz.\n",
  "144": "Emelkedett intraverzió.\nFügg a külsõ közegtõl, stressz-gyûjtés jellemzi.\nHiperaktivitásra hajlamos, nehezen alszik, pihen.\n",
  "145": "Természeti tipológiája egyensúlyban van.\nStressz-okozó, harmónia felbomlása.\nHarmónia felbomlása esetén betegségek: betegségcsoport keríti hatalmába.\n",
  "146": "Hajlamos a kockázatvállalásra, traumaveszély fenyegeti.\nStressz-oldás lényeges.\nMeg kell tanulnia az ellazulást.\n",
  "147": "Önszeretõ, nagyon érzékeny.\nBetegségeinek fõ oka komforthiány a családban és társadalomban.\nFontos a jó kommunikáció kialakítása.\n",
  "151": "Sztereotip viselkedésû.\nHajlamos a pedantikus ismétlõdõ folyamatok elfogadására.\nBetegség esetén depresszív állapotba kerülhet.\n",
  "152": "\"Magammal ragadom\" - ez jellemzi tevékenységét.\nEgészségét elsõsorban az új szituációkhoz való alkalmazkodás törheti meg.\nBetegség: adaptációs problémák.",
  "153": "Magas aktivitása kompenzálja az adaptációt.\nHa a mozgás nem biztosított, maga a gyógyulás folyamata legyen változatos.\nBetegség esetén nem kényszeríthetjük fekvésre.\n",
  "154": "Gyenge a test bal oldala és a jobb agyfélteke.\nElsõsorban a szív-és érrendszer valamint a gyomor és hasnyálmirigy betegségekre fogékony.\n",
  "155": "Harmonikus.\t\t\t\t\t\nÉrzelmi függõség, visszafogottság jellemzi.\nStressz-gyûjtõ, de jó az ellenálló képessége.\n",
  "161": "Inert, vegetatív tartalékok alacsonyak.\nÖsszegyüjti stresszt, majd robban.\nNehéz megmozgatni, ha kimozdult nehéz megnyugtatni.",
  "162": "Erõs temperamentum, hideg érzelem.\nÉrzelmi terhelés esetén váratlan reakciók.\nÁllapotváltoztatás csak szakaszosan, lassan.",
  "163": "Érzelmileg durva.\nMagas energetikája miatt az  érzelmi terhelés esetén váratlan reakciók.\nAz érzelmi tartalékokat nagyon gyorsan letöri.\n",
  "164": "Érzelmi stressz esetén, apátia.\nEnergia túlhasználás.\nA fekezés folyamatának, adaptációnak a törése.",
  "165": "Alacsony ellenállóképesség.\nAlacsony integrációs képesség.\nStresszokozó: a szociális vagy társadalmi közeg változása.",
  "166": "Szubjektív, kiegyensúlyozattlan.\nBelsõ konfliktusban van.\nHisztérikus reakciók lehetségesek.",
  "167": "Védtelenség, hipochondria.\nA betegségeket összegyüjti, alcsony tûrési határ.\nTartalékok hiánya jellemzi.",
  "211": "Okos, erõs kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nNem verbális módszerek fogadására alkalmas.\t\t\nAsztrális, mentális programozás (napfény, víz, fák, növények) hatékony.\n",
  "212": "Okos, erõs kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nAsztrális és mentális önprogramozást a mindennapi életébe kell beépíteni,\nmagas önprogramozási képesség jellemzi.\n",
  "213": "Okos, erõs kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nNehéz vele a munka mivel nagyon erõs az energetikája.\t\t\nJó az önszabályozó képessége.\nNem egy hálás típus  Ezt én csináltam.\n",
  "214": "Okos, erõs kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nSértõdékeny.\t\t\t\nHatásos a verbális, energetikai (impulzusszerûen) módszerek.\n",
  "215": "Okos, erõs kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nAsztrális és mentális önprogramozásra, és fizikai gyakorlatokra képes.\t\t\t\nBetegségei általában az életmódjával kapcsolatosak.\n",
  "216": "Okos, erõs kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nVerbálisan programozható.\nAsztrális, mentális önprogramozás jellemzi. Mezõráhatásokra érzékeny.\n",
  "217": "Okos, erõs kritikai, és világnézeti gát, magas önprogramozási képesség jellemzi.\nAz intellektum kiegyenlíti a temperamentum lehetõségeit.\t\nÉrzelmi támogatásra van szüksége.\n",
  "221": "Képzelõerõ, asztrális szintû programozás.\nTermészeti képeket használjunk (kép, zene, színekkel való munka).\nNyugodt tényezõkkel, periódikusan ismétlõdõ módszerekkel dolgozzunk.\n",
  "222": "Képzelõerõ, asztrális szintû programozás.\nAsztrális programozás, képek és természeti komponensek felhasználásával.\nRendszeres fizikai gyakorlatok fontosak.\n",
  "223": "Képzelõerõ, asztrális szintû programozás.\nErõs saját energetikája van.\t\t\t\t\nLegjobb megtanítani neki az energetikai gyakorlatokat.\n",
  "224": "Képzelõerõ, asztrális szintû programozás.\nAsztrális programozásra, képekkel való munkára fogékonnyá tenni.\n",
  "225": "Képzelõerõ, asztrális szintû programozás.\nÉrzékeny, beképzeli a betegségeket.\t\t\t\t\t\nAsztrális és energetikai programozás.\n",
  "226": "Képzelõerõ, asztrális szintû programozás.\nIngerlékeny, állandó stressz-állapotban van.\nGondolatban pszichológiai fészket kell találni neki, ahol elrejtõzhet.\n",
  "227": "Képzelõerõ, asztrális szintû programozás.\nHipochonder, érzékeny, a minimális ingereket is megérzi.\nPszicho-fizikai tréningek hatásosak.\n",
  "231": "Logikus bloksémák, mentális progr., torziós mezõkkel való munka fontos.\nFontos a munkák stabilitása, természeti rendszerekkel dolgozhatunk.\nFontos hogy a gyógykezelési programja ne változzon.\nEl kell juttatni a programot a páciens tudatáig, hogy azután saját maga ismételhesse.\n",
  "232": "Logikus bloksémák, mentális progr., torziós mezõkkel való munka fontos.\nVerbális és nem verbális munkamódszerek.\nFontos a munka stabilitása, ezen típus számára hasznos a programban visszatérõ formákat alkalmazunk.\n",
  "233": "Logikus bloksémák, mentális progr., torziós mezõkkel való munka fontos.\nNagyon magas a kritikai gát.\nJó a verbális munkamódszer: ima, ének.\nFontos a saját energetikájának aktiválása.Saját magát gyógyítja.\n",
  "234": "Logikus bloksémák, mentális progr., torziós mezõkkel való munka fontos.\nVerbális szuggesztív programozás, különösen a mentális síkon.\t\nImpulzusos energetikai ráhatás.\n",
  "235": "Logikus bloksémák, mentális progr., torziós mezõkkel való munka fontos.\nMagas az önszabályozási képessége, ezért minden módszert ezen keresztül kell végig vezetni.\n",
  "236": "Logikus bloksémák, mentális progr., torziós mezõkkel való munka fontos.\nJól irányítható verbális módszerekkel.\nMentális programozás.\nFigyelmet kell fordítani a túlfeszültség levételére.\n",
  "237": "Logikus bloksémák, mentális progr., torziós mezõkkel való munka fontos.\nStabil, megváltozhatatlan programmal kell dolgozni vele, önhelyreállításra kell helyezni a hangsúlyt.\n",
  "241": "Rendkívüli pedantizmus jellemzi (a gyógyítóra is ez legyen a jellemzõ).\nRészletesen, pontosan, logikusan kell a programot elmondani.\n",
  "242": "Minden munkamódszer hatékony vele, ha szuggesztív ráhatást alkalmazunk.\nHa verbális ráhatással dolgozunk, akkor energetikai módszerrel is ki kell egészíteni (saját energetikájával).\n",
  "243": "Verbális, vokális módszerrel és mentális programozással dolgozhatunk.\nDinamikus pszichoenergetikai módszereket is alkalmazhatunk.\n",
  "244": "Krónikus betegségek a baloldalon fognak jelentkezni.\nVerbális programozást alkalmazhatunk.\nEnergetikai ráhatást a gyengébbik oldalra, majd elosztjuk.\n",
  "245": "Önszabályozásra alkalmas, mert magas a tudati szintje.\nVerbális, mentális programozást alkalmazhatunk, energetikai módszer kiegészítésével.\n",
  "246": "Verbális módszerekkel rá kell vezetni a pozitív hozzáállásra.\nMentális programozást is alkalmazhatunk.\nKorrigálni kell az önszabályozását.\n",
  "247": "Magas érzékenység jellemzi.\nVerbális, logikai meggyõzést kell alkalmaznunk.\nMentális, verbális munkamódszerek alkalmazhatóak.\nEnergetikára nagyon érzékeny, vigyázni a dózis nagyságára.\n",
  "251": "Lassú eredmény várható.\nTermészeti módszereket és mentális programozást alkalmazhatunk.\n",
  "252": "Nagyon erõs a struktúrája.\nAsztrális, mentális programozást alkalmazhatunk, (képek, zene) energetikai módszerek kiegészítésével.\nFontos az energetikájának a harmonizálása.\n",
  "253": "Fizikai módszereket alkalmazhatunk (kontakt nélküli masszás, pont masszás, fizikai gyakorlatok).\nAsztrális, mentális módszereket is alkalmazhatunk (fizikai tartalékok aktivizálása).\n",
  "254": "A fékezés erejét kell növelni.\nMeg kell tanítani ellazulni.\nVerbális, asztrális, mentális programmódszereket alkalmazhatunk.\n",
  "255": "A környezeti hatások könnyen átprogramozzák. Asztrális, mentális\nprogramozással stabil programot alkalmazzunk. Fennáll a betegség \nvisszatérésének veszélye.",
  "256": "Könnyen irányítható,szuggesztív módszerekkel.\nSzámára a dinamikus programok a megfelelõek.\nLe kell venni a feszültséget, idõt kell hagyni az ellazulásra.\n",
  "257": "Állandó érzelmi támogatásra szorul.\nNe érje egyszerre nagy dózisú energetikai ráhatás, csak fokozatosan növeljük az energiát.\n",
  "261": "Mentális programozás.\nLerontja a saját temperamentumát.\nPszichofizikai gyakorlatokat és energetikai ráhatást alkalmazhatunk.\n",
  "262": "Mentális programozás.\nNehéz bekapcsolni a munkába.\t\nPszichofizikai gyakorlatokat és természeti erõket alkalmazhatunk (víz, fitoterápia).\n",
  "263": "Mentális programozás.\nMinden fizikai módszert alkalmazhatunk, verbális ráhatás kombinálásával.\nÉrzelmi kapaszkodók lényegesek.\n",
  "264": "Mentális programozás.\nParancsszerû utasításokkal dolgozhatunk, az érzelmi megerõsítés fontos (erre épüljön az egész program).\n",
  "265": "Mentális programozás.\nNem kritikus.\nA túlprogramozás veszélye fennállhat (a betegség visszatérhet).\n",
  "266": "Mentális programozás.\nA munka fizikai, érzelmi kontúr mentén a leghatékonyabb.\n",
  "267": "Mentális programozás.\nAprólékos, magyarázó munkamódszert alkalmazzunk, érzelmi támogatással.\nÉrzékeny, nem magabiztos.\n",
  "271": "Asztrális programozás.\nLerontja a saját temperamentumát.\nPszichofizikai gyakorlatokat és energetikai ráhatást alkalmazhatunk.\n",
  "272": "Asztrális programozás.\nNehéz bekapcsolni a munkába.\t\nPszichofizikai gyakorlatokat és természeti erõket alkalmazhatunk (víz, fitoterápia).\n",
  "273": "Asztrális programozás.\nMinden fizikai módszert alkalmazhatunk, verbális ráhatás kombinálásával.\nÉrzelmi kapaszkodók lényegesek.\n",
  "274": "Asztrális programozás.\nParancsszerû utasításokkal dolgozhatunk, az érzelmi megerõsítés fontos (erre épüljön az egész program).\n",
  "275": "Asztrális programozás.\nNem kritikus.\t\t\t\t\t\t\t\t\nA túlprogramozás veszélye fennállhat (a betegség visszatérhet).\n",
  "276": "Asztrális programozás.\nA munka fizikai, érzelmi kontúr mentén a leghatékonyabb.\n",
  "277": "Asztrális programozás.\nAprólékos, magyarázó munkamódszert alkalmazzunk, érzelmi támogatással.\nÉrzékeny, nem magabiztos.\n",
  "nincs": "Nem találom a forrás adatokat."
};
