// A kronobiológiai kalkulátor normatív marker-táblája a mellékelt forráscsomaggal
// összevetett, statikus adatkészletként kerül a kliensbe; nincs hálózati kérés.
export interface NormativeProfile { right: number; left: number; label: string; }
export const normativeProfiles: Record<"physical" | "emotional" | "intellectual", Record<number, NormativeProfile>> = 
{
  physical: {
    1: { right: 35, left: 55, label: "Közepesen szangvinikus" },
    2: { right: 55, left: 72, label: "Szangvinikus" },
    3: { right: 15, left: 65, label: "Kolerikus" },
    4: { right: 50, left: 72, label: "Szangvinikus" },
    5: { right: 30, left: 41, label: "Közepesen szangvinikus" },
    6: { right: 75, left: 21, label: "Flegmatikus" },
    // Az eredeti MARKERS.J1 értéke 45/72; az Excel ettől eltér.
    7: { right: 45, left: 72, label: "Szangvinikus" },
    8: { right: 60, left: 22, label: "Flegmatikus" },
    9: { right: 35, left: 28, label: "Melankólikus" },
    10: { right: 35, left: 49, label: "Közepesen szangvinikus" },
    11: { right: 95, left: 22, label: "Flegmatikus" },
    12: { right: 30, left: 99, label: "Kolerikus" },
    13: { right: 40, left: 61, label: "Közepesen szangvinikus" },
    14: { right: 20, left: 55, label: "Kolerikus" },
    15: { right: 40, left: 28, label: "Melankólikus" },
    16: { right: 90, left: 21, label: "Flegmatikus" },
    17: { right: 50, left: 83, label: "Szangvinikus" },
    18: { right: 10, left: 45, label: "Érzékeny kolerikus" },
    19: { right: 99, left: 55, label: "Flegmatikus szangvinikus" },
    20: { right: 30, left: 52, label: "Közepesen szangvinikus" },
    21: { right: 20, left: 79, label: "Kolerikus" },
    22: { right: 80, left: 69, label: "Flegmatikus szangvinikus" },
    23: { right: 25, left: 21, label: "Melankólikus" },
  },
  emotional: {
    1: { right: 69, left: 95, label: "Szenvedélyes" },
    2: { right: 75, left: 27, label: "Egoisztikus vezető" },
    3: { right: 31, left: 45, label: "Empatikus" },
    4: { right: 62, left: 77, label: "Szenvedélyes" },
    5: { right: 50, left: 59, label: "Empatikus" },
    6: { right: 44, left: 68, label: "Empatikus" },
    7: { right: 12, left: 45, label: "Önfeláldozó" },
    8: { right: 6, left: 23, label: "Hideg" },
    9: { right: 81, left: 54, label: "Egoisztikus vezető" },
    10: { right: 25, left: 77, label: "Önfeláldozó" },
    11: { right: 18, left: 50, label: "Önfeláldozó" },
    12: { right: 44, left: 59, label: "Empatikus" },
    13: { right: 25, left: 68, label: "Önfeláldozó" },
    14: { right: 50, left: 77, label: "Szenvedélyes" },
    15: { right: 50, left: 99, label: "Szenvedélyes" },
    16: { right: 50, left: 36, label: "Szentimentális" },
    17: { right: 56, left: 41, label: "Szentimentális" },
    18: { right: 31, left: 14, label: "Hideg" },
    19: { right: 99, left: 54, label: "Egoisztikus vezető" },
    20: { right: 44, left: 32, label: "Szentimentális" },
    21: { right: 62, left: 41, label: "Szentimentális" },
    22: { right: 25, left: 18, label: "Hideg" },
    23: { right: 69, left: 59, label: "Egoisztikus vezető" },
    24: { right: 56, left: 41, label: "Szentimentális" },
    25: { right: 44, left: 68, label: "Empatikus" },
    26: { right: 37, left: 41, label: "Hideg" },
    27: { right: 56, left: 73, label: "Szenvedélyes" },
    28: { right: 44, left: 73, label: "Empatikus" },
  },
  intellectual: {
    1: { right: 64, left: 35, label: "Produktív Művészi" },
    2: { right: 21, left: 65, label: "Gondolkodó" },
    3: { right: 21, left: 65, label: "Gondolkodó" },
    4: { right: 93, left: 82, label: "Produktív Vegyes" },
    5: { right: 43, left: 41, label: "Harmonikus vegyes" },
    6: { right: 0, left: 99, label: "Gondolkodó" },
    7: { right: 57, left: 88, label: "Produktív Gondolkodó" },
    8: { right: 7, left: 41, label: "Gyakorlati Gondolkodó" },
    9: { right: 29, left: 35, label: "Gyakorlati Gondolkodó" },
    10: { right: 86, left: 35, label: "Produktív Művészi" },
    11: { right: 29, left: 82, label: "Gondolkodó" },
    12: { right: 86, left: 41, label: "Produktív Művészi" },
    13: { right: 14, left: 71, label: "Gondolkodó" },
    14: { right: 50, left: 59, label: "Harmonikus vegyes" },
    15: { right: 78, left: 65, label: "Produktív Vegyes" },
    16: { right: 93, left: 24, label: "Produktív Művészi" },
    17: { right: 84, left: 71, label: "Produktív Vegyes" },
    18: { right: 29, left: 41, label: "Gyakorlati Gondolkodó" },
    19: { right: 26, left: 71, label: "Gondolkodó" },
    20: { right: 99, left: 82, label: "Produktív Vegyes" },
    21: { right: 7, left: 76, label: "Gondolkodó" },
    22: { right: 14, left: 35, label: "Produktív Vegyes" },
    23: { right: 50, left: 65, label: "Produktív Gondolkodó" },
    24: { right: 26, left: 18, label: "Gyakorlati Művészi" },
    25: { right: 29, left: 88, label: "Gondolkodó" },
    26: { right: 93, left: 59, label: "Produktív Művészi" },
    27: { right: 57, left: 82, label: "Produktív Gondolkodó" },
    28: { right: 29, left: 29, label: "Gyakorlati Vegyes" },
    29: { right: 29, left: 88, label: "Gondolkodó" },
    30: { right: 71, left: 47, label: "Produktív Művészi" },
    31: { right: 7, left: 35, label: "Gyakorlati Gondolkodó" },
    32: { right: 64, left: 59, label: "Produktív Vegyes" },
    33: { right: 29, left: 82, label: "Gondolkodó" },
  },
};
